In [1]:
import numpy as np
import tensorflow as tf
import tensorflow.keras as keras

data = np.random.randint(0, 256, (28, 28, 1))
print(data.shape)
print(type(data))

(28, 28, 1)
<class 'numpy.ndarray'>


In [2]:
data_tf = tf.convert_to_tensor(data, dtype=tf.float32)
print(data_tf.shape)
print(type(data_tf))

(28, 28, 1)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [3]:
conv_layer = keras.layers.Conv2D(filters=1, 
                                kernel_size=(3, 3))

output = conv_layer(data_tf)
print(output.shape)

ValueError: Input 0 of layer "conv2d" is incompatible with the layer: expected min_ndim=4, found ndim=3. Full shape received: (28, 28, 1)

In [4]:
data_tf = tf.reshape(data_tf, (1, 28, 28, 1))
print(data_tf.shape)

(1, 28, 28, 1)


In [5]:
conv_layer = keras.layers.Conv2D(filters=1, 
                                kernel_size=(3, 3),
                                activation='relu')
output = conv_layer(data_tf)
print(output.shape)
print(output[0, :,:,0])

(1, 26, 26, 1)
tf.Tensor(
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 1.86799622e+02 0.00000000e+00 0.00000000e+00
  2.08246765e+01 0.00000000e+00 0.00000000e+00 0.00000000e+00
  2.91265411e+01 0.00000000e+00 1.36772705e+02 0.00000000e+00
  0.00000000e+00 2.68810272e+00 1.89737610e+02 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 9.05178642e+00
  0.00000000e+00 0.00000000e+00]
 [3.07840691e+01 0.00000000e+00 3.31922722e+01 6.80950623e+01
  0.00000000e+00 6.76597443e+01 1.13904953e+01 0.00000000e+00
  5.90294266e+01 0.00000000e+00 0.00000000e+00 0.00000000e+00
  2.47820911e+01 0.00000000e+00 3.11685944e+01 1.29024162e+01
  0.00000000e+00 1.98132706e+00 7.29557800e+01 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [2.94534969e+01 0.00000000e+00 0.00000000e+00 1.32758408e+02
  0.00000000e+00 0.00000000e+00 4.01719627e+01 0.00000000e+00
  0.00000000e+00 8.60109329e-01 2.647447

In [6]:
weights = conv_layer.get_weights()
print(type(weights))
print(len(weights))

<class 'list'>
2


In [7]:
print(weights[0].shape)

(3, 3, 1, 1)


In [8]:
print(weights[0].shape)
print(weights[1].shape)

(3, 3, 1, 1)
(1,)


In [9]:
print(weights[0][:,:,0,0])
print(weights[1])

[[-0.16688204  0.07040244 -0.2743608 ]
 [-0.39717773  0.3866539  -0.00657821]
 [-0.28966415  0.12648255  0.43998384]]
[0.]


## stride

In [10]:
data_tf = tf.reshape(data_tf, (1, 28, 28, 1))
print(data_tf.shape)

(1, 28, 28, 1)


In [11]:
conv_layer = keras.layers.Conv2D(filters=5, 
                                kernel_size=(3, 3), 
                                strides=2)
output = conv_layer(data_tf)
print(output.shape)

(1, 13, 13, 5)


In [12]:
conv_layer = keras.layers.Conv2D(filters=1, 
                                kernel_size=(4, 4), 
                                strides=2)
output = conv_layer(data_tf)
print(output.shape)

(1, 13, 13, 1)


In [13]:
conv_layer = keras.layers.Conv2D(filters=1, kernel_size=(5, 5), strides=2)
output = conv_layer(data_tf)
print(output.shape)

(1, 12, 12, 1)
